#!/bin/bash

WDIR=`pwd`

export GAZEBO_PLUGIN_PATH=${WDIR}/plugins:${GAZEBO_PLUGIN_PATH}
export GAZEBO_MODEL_PATH=${WDIR}/models:${GAZEBO_MODEL_PATH}

mkdir -p ~/.black_swift
cp models/e2/param ~/.black_swift/param_mr_0x41000002.bst

pkill gcsDaemon
pkill pro_core

bin/gcsDaemon -n 55554 -S &
bin/pro_core_swil_MULTIROTOR -i localhost &
# -v6 &

gazebo worlds/multirotor.world

echo "Killing gcsDaemon ..."
pkill gcsDaemon 
echo "Killing autopilot SWIL ..."
pkill pro_core
